version: "3"
services:
  streamlit-service: # TODO: CHANGE NAME
    image: streamlit_template_image # TODO: CHANGE NAME
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_template_container

    volumes:
      - .:/workspace:cached